name: Build and deploy ASP.Net Core app to Azure Web App - pov-api-service

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check directory structure
        run: ls -R

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./PovVoyage  # Set correct project folder

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
        working-directory: ./PovVoyage

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./PovVoyage

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./PovVoyage/publish  # Ensure correct path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pov-api-service'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
